version: 0.0
os: linux

files:
  - source: /
    destination: /opt/nodejs-app

hooks:
  BeforeInstall:
    - location: deployment-scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment-scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deployment-scripts/stop_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: deployment-scripts/validate_service.sh
      timeout: 300
      runas: root