version: '3.7'

services:
  # Changed service name from 'environment' to 'app'
  app:
    # Removed 'build' section
    # Reference the ECR image. The image URI will be passed to the script.
    image: 381491851900.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest

    ports:
      - "3005:3005" # Correct port mapping

    # Removed development-specific settings
    # Removed redundant command

    environment:
      - NODE_ENV=production
      - PORT=3005 # Explicitly set the port environment variable

    restart: unless-stopped # Recommended to restart the container if it stops
